"""Add indices

Revision ID: cfcaf1314dc0
Revises: 17531f859663
Create Date: 2025-09-22 08:12:26.254864

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cfcaf1314dc0"
down_revision: Union[str, Sequence[str], None] = "17531f859663"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_artifact_title"), "artifact", ["title"], unique=False)
    op.create_index(op.f("ix_artifact_url"), "artifact", ["url"], unique=False)
    op.create_index(op.f("ix_tag_name"), "tag", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tag_name"), table_name="tag")
    op.drop_index(op.f("ix_artifact_url"), table_name="artifact")
    op.drop_index(op.f("ix_artifact_title"), table_name="artifact")
    # ### end Alembic commands ###
